# 站点基本设置
title: "海上升明月"
name: "海上升明月"
description: "记录技术与生活的点点滴滴"
locale: "zh-CN"
url: "https://seamoonappear.github.io"
baseurl: "/boke"

# 作者信息
author:
  name: "王维"
  avatar: "/boke/assets/images/bio-photo.jpg"
  bio: "一个热爱技术与分享的开发者"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/seamoonappear"

# 主题设置
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"
search: true

# 移除 Follow 按钮
follow:
  button: false

# 评论设置 (Giscus配置)
comments:
  provider: "giscus"
  giscus:
    repo: "seamoonappear/boke"
    repo-id: ""  # 需要在Giscus官网获取
    category: "Announcements"
    category-id: ""  # 需要在Giscus官网获取
    mapping: "pathname"
    reactions-enabled: "1"
    theme: "preferred_color_scheme"
    emit-metadata: "0"
    input-position: "bottom"
    lang: "zh-CN"

# 默认 Front Matter
defaults:
  # 对所有文章应用的默认设置
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      show_date: true
  # 对页面应用的默认设置
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

# 插件
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# 网站设置
sitemap: true
feed:
  path: atom.xml

# 分页设置
paginate: 5
paginate_path: /page:num/

# 构建设置
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# 包含的文件和目录
include:
  - _pages
  - .well-known
  - _includes
  - _sass
  - assets

# 排除的文件和目录
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/scripts.min.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - vendor
  - Gemfile.lock

# 集合配置
collections:
  posts:
    output: true
    permalink: /:categories/:title/

# 分类和标签存档
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# 社交媒体分享 (可选)
social:
  type: Person
  name: "王维"
  links:
    - "https://github.com/seamoonappear"

# 网站图标
favicon: /assets/images/favicon.ico

# 搜索引擎优化
seo:
  name: "海上升明月"
  description: "记录技术与生活的点点滴滴"
  author: "王维"
  social:
    name: "王维"
    links:
      - "https://github.com/seamoonappear"

# 网站头部设置
header:
  overlay_image: /assets/images/header-bg.jpg  # 可选头部背景图
  overlay_filter: 0.5  # 背景图遮罩透明度
  actions:
    - label: "了解更多"
      url: "/about/"

# 页脚设置
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/seamoonappear"
    - label: "关于"
      icon: "fas fa-fw fa-user"
      url: "/about/"

# 阅读时间设置
read_time: true

# 相关文章设置
related: true

# 分享按钮设置
share: true

# 文章导航设置
post_pagination: true

# 语法高亮设置
syntax_highlighter: rouge
syntax_highlighter_opts:
  block:
    line_numbers: true

# 图片路径设置
image_path: /assets/images/

# 默认图片 (可选)
default_image:
  path: "/assets/images/bio-photo.jpg"
  caption: "默认图片说明"

# 网站统计 (可选)
analytics:
  provider: "google"
  google:
    tracking_id: ""  # 你的Google Analytics跟踪ID

# 网站验证 (可选)
webmaster_verifications:
  google: ""  # 你的Google网站验证码
  bing: ""    # 你的Bing网站验证码
  alexa: ""   # 你的Alexa验证码
  yandex: ""  # 你的Yandex验证码

# 额外的head内容 (可选)
head_scripts:
  - /assets/js/custom.js

# 额外的样式 (可选)
extra_css:
  - /assets/css/custom.css

# 网站时区
timezone: Asia/Shanghai

# 网站语言
lang: zh-CN

# 网站编码
encoding: utf-8

# 网站构建时忽略的文件
ignore_files:
  - README.md
  - LICENSE
  - CNAME
  - .gitignore

# 自定义变量
custom:
  site_description: "个人技术博客，分享开发经验和生活感悟"
  site_keywords: "技术,编程,开发,博客,学习"
  copyright: "© 2025 海上升明月. 基于Minimal Mistakes主题构建."